<a href="https://colab.research.google.com/github/auebgeorge/EKPA/blob/main/Diabetes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
data = pd.read_csv('https://raw.githubusercontent.com/kdemertzis/EKPA/main/Data/phishing_dataset.csv', delimiter=',')

In [2]:
data = data.sample(frac=1).reset_index(drop=True)
data.head()

Domain  Have_IP  Have_At  URL_Length  URL_Depth  Redirection  \
0  poonammishra.in        0        0           0          3            0   
1      mirtesen.ru        0        0           1          1            0   
2      twitter.com        0        0           1          1            0   
3   techcrunch.com        0        0           1          3            0   
4   persianblog.ir        0        0           1          3            0   

   https_Domain  TinyURL  Prefix/Suffix  DNS_Record  Web_Traffic  Domain_Age  \
0             0        0              0           0            1           0   
1             0        0              0           0            1           0   
2             0        0              0           0            1           1   
3             0        0              0           0            1           1   
4             0        0              0           1            1           1   

   Domain_End  iFrame  Mouse_Over  Right_Click  Web_Forwards  Label  
0           1       1           0            1             0      1  
1           1       0           0            1             0      0  
2           1       0           0            1             0      0  
3           1       0           0            1             0      0  
4           1       1           1            1             1      0

In [3]:
X = data.drop(['Domain', 'Label'], axis=1)

In [4]:
X.head()

Have_IP  Have_At  URL_Length  URL_Depth  Redirection  https_Domain  \
0        0        0           0          3            0             0   
1        0        0           1          1            0             0   
2        0        0           1          1            0             0   
3        0        0           1          3            0             0   
4        0        0           1          3            0             0   

   TinyURL  Prefix/Suffix  DNS_Record  Web_Traffic  Domain_Age  Domain_End  \
0        0              0           0            1           0           1   
1        0              0           0            1           0           1   
2        0              0           0            1           1           1   
3        0              0           0            1           1           1   
4        0              0           1            1           1           1   

   iFrame  Mouse_Over  Right_Click  Web_Forwards  
0       1           0            1             0  
1       0           0            1             0  
2       0           0            1             0  
3       0           0            1             0  
4       1           1            1             1

In [6]:
#y=np.ravel(data['Label'])
y=np.ravel(data['Label'])

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=43)

In [8]:
# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
# Define classifiers
classifiers = [
    LogisticRegression(),
    SVC(),
    RandomForestClassifier(),
    MLPClassifier(),
    KNeighborsClassifier(),
    DecisionTreeClassifier()
]

In [10]:
# Evaluate and compare classifiers
results = {'Classifier': [], 'Accuracy': [], 'Precision': [], 'Recall': [], 'F1 Score': []}

for clf in classifiers:
    clf_name = clf.__class__.__name__

    # Train the classifier
    clf.fit(X_train, y_train)

    # Make predictions
    y_pred = clf.predict(X_test)

    # Calculate evaluation metrics
    acc = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')

    # Confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    # Display results
    print(f"\n{clf_name} Metrics:")
    print(f"Accuracy: {acc}")
    print(f"Precision: {precision}")
    print(f"Recall: {recall}")
    print(f"F1 Score: {f1}")
    print("Confusion Matrix:")
    print(cm)

    # Store results for comparison
    results['Classifier'].append(clf_name)
    results['Accuracy'].append(acc)
    results['Precision'].append(precision)
    results['Recall'].append(recall)
    results['F1 Score'].append(f1)


LogisticRegression Metrics:
Accuracy: 0.7966666666666666
Precision: 0.8290523816196212
Recall: 0.7966666666666666
F1 Score: 0.7923754626970776
Confusion Matrix:
[[1396   73]
 [ 537  994]]

SVC Metrics:
Accuracy: 0.8246666666666667
Precision: 0.863147771092498
Recall: 0.8246666666666667
F1 Score: 0.8206072896938337
Confusion Matrix:
[[1448   21]
 [ 505 1026]]

RandomForestClassifier Metrics:
Accuracy: 0.858
Precision: 0.8719781645098913
Recall: 0.858
F1 Score: 0.8569835455982152
Confusion Matrix:
[[1399   70]
 [ 356 1175]]

MLPClassifier Metrics:
Accuracy: 0.8516666666666667
Precision: 0.866325310598889
Recall: 0.8516666666666667
F1 Score: 0.8505269370614216
Confusion Matrix:
[[1394   75]
 [ 370 1161]]

KNeighborsClassifier Metrics:
Accuracy: 0.854
Precision: 0.8676494651624824
Recall: 0.854
F1 Score: 0.8529715897588528
Confusion Matrix:
[[1392   77]
 [ 361 1170]]

DecisionTreeClassifier Metrics:
Accuracy: 0.8553333333333333
Precision: 0.8704300818236104
Recall: 0.8553333333333333
F1 S

In [11]:
# Display comparison results
results_df = pd.DataFrame(results)
results_df = results_df.sort_values(by='Accuracy', ascending=False)
print("\nComparison of Classifiers:")
print(results_df)


Comparison of Classifiers:
               Classifier  Accuracy  Precision    Recall  F1 Score
2  RandomForestClassifier  0.858000   0.871978  0.858000  0.856984
5  DecisionTreeClassifier  0.855333   0.870430  0.855333  0.854196
4    KNeighborsClassifier  0.854000   0.867649  0.854000  0.852972
3           MLPClassifier  0.851667   0.866325  0.851667  0.850527
1                     SVC  0.824667   0.863148  0.824667  0.820607
0      LogisticRegression  0.796667   0.829052  0.796667  0.792375
